use work;
-- WRITE A QUERY TO DISPLAY THE FIRST 3 CHARACTERS OF EACH EMPLOYEE'S NAME
select left(emp_name,3)
from employee;
-- WRITE A QUERY TO DISPLAY EMPLOYEE NAMES IN UPPERCASE AND LOWERCASE
select upper(emp_name),lower(emp_name)
from employee;
-- WRITE A QUERY TO FIND THE LENGTH OF EACH EMPLOYEE'S NAME
select char_length(emp_name)
from employee;
-- WRITE A QUERY TO DISPLAY EMPLOYEE NAMES AFTER REMOVING LEADING AND TRAILING SPACES
select trim(emp_name)
from employee;
-- WRITE A QUERY TO REPLACE THE WORD MANAGER WITH DEVELOPER IN THE JOB TITLE
select replace(job_title,"Manager","Developer")
from employee;
-- WRITE A QUERY TO DISPLAY THE FIRST NAME AND LAST NAME SEPARATELY WHEN THE EMPLOYEE NAME IS STORED IN A SINGLE COLUMN

-- WRITE A QUERY TO FIND EMPLOYEES WHOSE NAMES START WITH A AND END WITH N USING STRING 
select emp_name from employee
where left(emp_name,1)='A' AND
right(emp_name,1)='n';
-- WRITE A QUERY TO CONCATENATE AN EMPLOYEE'S FIRST NAME, LAST NAME, AND DEPARTMENT NAME INTO ONE COLUMN CALLED EMPLOYEE_DETAILS
select concat(emp_name,' - ',department)as EMPLOYEE_DETAILS
from employee;
-- DATE & TIME FUNCTIONS
-- WRITE A QUERY TO DISPLAY THE CURRENT DATE AND CURRENT DATE AND TIME
select curdate() as currentdate,now() as currentDateTime;

ALTER TABLE EMPLOYEE ADD HIRE_DATE DATE;
UPDATE EMPLOYEE
SET HIRE_DATE="2023-10-15"
WHERE EMP_ID=101;
UPDATE EMPLOYEE
SET HIRE_DATE="2025-09-05"
WHERE EMP_ID=102;
UPDATE EMPLOYEE
SET HIRE_DATE="2020-01-11"
WHERE EMP_ID=103;
UPDATE EMPLOYEE
SET HIRE_DATE="2022-10-25"
WHERE EMP_ID=104;
UPDATE EMPLOYEE
SET HIRE_DATE="2019-02-22"
WHERE EMP_ID=106;
UPDATE EMPLOYEE
SET HIRE_DATE="2023-01-12"
WHERE EMP_ID=107;
select * from employee;
-- WRIE A QUERY TO DISLAY THE YEAR,MONTH AND DAY SEPARATELY FROM AN EMPLOYEE TABLE
select year(hire_date) as year,
		month(hire_date) as month,
        day(hire_date) as day
from employee;
-- WRITE A QUERY TO FIND EMPLOYEES WHO JOINED IN THE YEAR 2023
select * from employee
where year(hire_date)=2023;
-- NUMBER OF YEARS EACH EMPLOYEE HAS WORKED IN THE COMPANY
select emp_name,timestampdiff(year,hire_date,curdate())as years_worked
from employee;
-- WRITE A QUERY TO FIND EMPLOYEES WHO JOINED THE COMPANY MORE THAN 5 YEARS AGO
select emp_name,timestampdiff(year,hire_date,curdate())as years_worked
from employee
WHERE timestampdiff(year,hire_date,curdate())>5;
-- WRITE A QUERY TO DISPLAY THE DAY NAME ON WHICH EMPLOYEE JOINED
SELECT DAYNAME(hire_date) from employee;


ALTER TABLE EMPLOYEE ADD dob DATE;
UPDATE EMPLOYEE
SET DOB="2000-10-15"
WHERE EMP_ID=101;
UPDATE EMPLOYEE
SET dob="2001-09-05"
WHERE EMP_ID=102;
UPDATE EMPLOYEE
SET DOB="1999-01-11"
WHERE EMP_ID=103;
UPDATE EMPLOYEE
SET DOB="2003-10-25"
WHERE EMP_ID=104;
UPDATE EMPLOYEE
SET DOB="1995-02-12"
WHERE EMP_ID=106;
UPDATE EMPLOYEE
SET DOB="2000-01-2"
WHERE EMP_ID=107;
-- WRITE A QUERY TO CALCULATE THE EXPECTED RETIREMENT DATE, MEASURING RETIREMENT IS AFTER 60 YEARS FROM DATEOFBIRTH
select emp_name,date_add(dob,INTERVAL 60 YEAR) as retirement_date
from employee;
